[package]
name = "lolcat"
version = "1.5.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[dependencies]
palette = "0.4.1"
rand = { version = "0.7.0", features = ["std", "small_rng"] }
structopt = "0.2.18"
unicode-segmentation = "1.3.0"
unicode-width = "0.1.5"

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12"
