[package]
name = "lcat"
version = "0.1.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[features]
default = ["structopt"]

[dependencies]
bstr = "0.2"
rand = { version = "0.7", features = ["std", "small_rng"] }
scarlet = "1.1"
structopt = { version = "0.3", optional = true }
unicode-width = "0.1"
unicode-segmentation = "1.3"

