[package]
name = "lcat"
version = "0.2.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"
description = "Another lolcat in rust! Full unicode support, escapes for ANSI escape sequences, hue shift in CIE L*C*h."
readme = "README.md"
repository = "https://github.com/davidkna/lcat-rs"
license = "MIT OR Apache-2.0"

[features]
default = ["structopt"]

[dependencies]
bstr = "0.2"
rand = { version = "0.7", features = ["std", "small_rng"] }
scarlet = "1.1"
structopt = { version = "0.3", optional = true }
unicode-width = "0.1"
unicode-segmentation = "1.3"

# Allocator
mimalloc = { version = "0.1.19", optional = true, default-features = false }
