cargo-features = ["edition"]

[package]
name = "lolcat"
version = "0.3.0"
authors = ["David Knaack <davidkna@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.5.4"
structopt = "0.2.10"
termcolor = "1.0.1"
vte = "0.3.2"